# Generated by Django 3.2.2 on 2021-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(max_length=200)),
                ('descrição_do_serviço', models.TextField()),
                ('CNPJ', models.TextField()),
                ('número_da_nota', models.CharField(max_length=256)),
                ('data_e_hora_da_emissão', models.CharField(max_length=200)),
                ('valor_da_nota', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
